# Generated by Django 5.2.6 on 2025-09-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='faculty_department',
            field=models.CharField(blank=True, choices=[('COMPUTING', 'Computing'), ('SST', 'SST')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='faculty_streams',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='hod_department',
            field=models.CharField(blank=True, choices=[('COMPUTING', 'Computing'), ('SST', 'SST')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='infra_building',
            field=models.CharField(blank=True, choices=[('NEW', 'New Building'), ('SCHOOL', 'School Building'), ('GU', 'GU Building')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='staff_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='working_at',
            field=models.CharField(blank=True, choices=[('STUDENT_COMMITTEE', 'Student Committee'), ('TEACHING_FACULTY', 'Teaching Faculty'), ('STAFF_MEMBER', 'Staff Member'), ('INFRA_MANAGER', 'Infrastructure Manager'), ('ADMIN_OFFICE', 'Admin Office'), ('HOD', 'HOD')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty'), ('HOD', 'HOD'), ('ADMIN', 'Admin'), ('STAFF', 'Staff')], default='STUDENT', max_length=10),
        ),
    ]
